### ISSUE TITLE
Getting AttributeError with python-novaclient 2.21.0

### ISSUE THREAD

**Issue by waky79** [rackspace/pyrax#542]
When using credentials file I get:
```python
Traceback (most recent call last):
    pyrax.set_credential_file(location, region)
  File "/usr/local/lib/python2.7/dist-packages/pyrax/__init__.py", line 429, in _wrapped
    return fnc(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyrax/__init__.py", line 525, in set_credential_file
    connect_to_services(region=region)
  File "/usr/local/lib/python2.7/dist-packages/pyrax/__init__.py", line 616, in connect_to_services
    cloudservers = connect_to_cloudservers(region=region)
  File "/usr/local/lib/python2.7/dist-packages/pyrax/__init__.py", line 665, in connect_to_cloudservers
    extensions = cs_shell._discover_extensions("1.1")
  File "/usr/local/lib/python2.7/dist-packages/novaclient/shell.py", line 471, in _discover_extensions
    self._discover_via_entry_points()):
  File "/usr/local/lib/python2.7/dist-packages/novaclient/shell.py", line 485, in _discover_via_python_path
    module = module_loader.load_module(name)
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/usr/local/lib/python2.7/dist-packages/os_networksv2_python_novaclient_ext.py", line 41, in <module>
    @utils.arg('network_id', metavar='<network_id>', help='ID of network')
AttributeError: 'module' object has no attribute 'arg'
```

**Comment by coreypobrien** [comment]
+1 Even if you're not using cloudservers, this is a blocker

**Comment by sivel** [comment]
The problem is not with pyrax, but 2 modules that `rackspace-novaclient` is dependent on:

1. os-networksv2-python-novaclient-ext
1. os-virtual-interfacesv2-python-novaclient-ext

Removing those packages for now should resolve the issue:

```
pip uninstall os-networksv2-python-novaclient-ext os-virtual-interfacesv2-python-novaclient-ext
```

**Comment by sivel** [comment]
See:

1. https://github.com/rackerlabs/os_networksv2_python_novaclient_ext/pull/4
1. https://github.com/Cerberus98/os_virtual_interfacesv2_ext/pull/3

**Comment by sivel** [comment]
Just as another option, downgrading to an older version of python-novaclient such as 2.20.0 should also resolve the issue.

**Comment by sivel** [comment]
Ok, it appears as though new versions of the affected extensions were just pushed to pypi.

`pip install -U os-networksv2-python-novaclient-ext==0.24 os-virtual-interfacesv2-python-novaclient-ext==0.18 python-novaclient==2.21.0`

Please let me know if this is resolving the issue for you.

**Comment by waky79** [comment]
Hi,

Sorry for late response. Yes, I resolved the issue at the time with the python-novaclient==0.21.0 requirement. I just wanted to log the issue here so the issue would be known.

Thanks sivel for the tips!
