### ISSUE TITLE
novaclient.v1_1 deprecated

### ISSUE THREAD

**Issue by giuseppe7** [rackspace/pyrax#544]
Hi all,

I'm seeing novaclient deprecation warnings, is pyrax work underway for using novaclient.v2?

pyrax==1.9.3

venv/lib/python2.7/site-packages/novaclient/v1_1/__init__.py:30: UserWarning: Module novaclient.v1_1 is deprecated (taken as a basis for novaclient.v2). The preferable way to get client class or object you can find in novaclient.client module.
  warnings.warn("Module novaclient.v1_1 is deprecated (taken as a basis for "

**Comment by sivel** [comment]
novaclient 2.21.0 deprecated the v1.1 client, and is issuing that warning. In novaclient 2.21.0, the v1.1 client is now an alias to the v2 client.

We will need to test more to validate that there are no backwards incompatible changes, and if so, potentially, make novaclient 2.20.0 a pinned dependency in pyrax for the time being.

**Comment by doublerr** [comment]
+1 on getting this resolved. I was setting up a new laptop and ran into this tonight. 

for what it's worth, `rackspace-novaclient` brings in latest `python-novaclient` as well

**Comment by sivel** [comment]
I've started some investigation into what would be required to prevent the warning.

One of the `rackspace-novaclient` dependencies will still cause the warning regardless of the changes made in pyrax.  There is however an open PR for it:

https://github.com/rackerlabs/os_diskconfig_python_novaclient_ext/pull/5

**Comment by kawikao** [comment]
So 1990's. I hope they fix it soon

**Comment by aaronmehar** [comment]
@sivel is there any new development on this?

**Comment by tr3buchet** [comment]
Since this is such a hoser, and since I don't really care, I have solved (hacked) this problem away with a bashscript:

```
#!/bin/bash                                                                                        
                                                                                                   
supernova $@ 2>&1 | grep -v "InsecureRequestWarning\|novaclient.v1_1\|keystoneclient\|Error Output"
```

Eventually, if these issues go away, i'll stop using it.

**Comment by therealmarv** [comment]
This is getting worse. Now it's not only annoying it breaks pyrax!
On 2015-12-18 [python-novaclient 3.0 was released](https://pypi.python.org/pypi/python-novaclient/3.0.0) (now 3.1) which removed novaclient.1_1 and now breaks pyrax!

Output:
```
$ python run.py
Slave binds are misssing, adding Master as slave too.
Traceback (most recent call last):
  File "run.py", line 21, in <module>
    app = create_app()
  File "/Users/marvin/pybossa/pybossa/pybossa/core.py", line 42, in create_app
    setup_uploader(app)
  File "/Users/marvin/pybossa/pybossa/pybossa/core.py", line 120, in setup_uploader
    from pybossa.uploader.rackspace import RackspaceUploader
  File "/Users/marvin/pybossa/pybossa/pybossa/uploader/rackspace.py", line 26, in <module>
    import pyrax
  File "/Users/marvin/pybossa/pybossa/env/lib/python2.7/site-packages/pyrax/__init__.py", line 60, in <module>
    from novaclient.v1_1 import client as _cs_client
ImportError: No module named v1_1
```

The PR https://github.com/rackspace/pyrax/pull/547 needs to be merged or please do some other fixes. Thanks.

**Comment by briancurtin** [comment]
it's fixed in 1.9.6 - somehow the change didn't properly get merged into what got released as 1.9.5

**Comment by kevin1024** [comment]
Well, this ruined my day in a pretty bad way - I had 1.9.5 pinned, it used to work, and suddenly stopped working.  If this were an open source project I wouldn't complain, but this is commercially supported software!

**Comment by pembo13** [comment]
PyRax seems to be more broken now. With the latest version of novaclient, I'm getting

`novaclient.exceptions.Forbidden: 'novaclient.v2.client.Client' is not designed to be initialized directly. It is inner class of novaclient. You should use 'novaclient.client.Client' instead. Related lp bug-report: 1493576`

**Comment by briancurtin** [comment]
python-novaclient is pinned at 2.27.0 for that reason
