### ISSUE TITLE
Newest python-novaclient 2.28.1 breaks pyrax and whole program

### ISSUE THREAD

**Issue by therealmarv** [rackspace/pyrax#575]
Again an underlying library has been updated and pyrax breaks the whole program.

The error message:
```
AttributeError: 'OpenStackComputeShell' object has no attribute '_discover_extensions'
```

Full error message from our project https://github.com/PyBossa/pybossa
```
15:06 $ python run.py
Slave binds are misssing, adding Master as slave too.
/Users/marvin/pybossa/pybossa/env/lib/python2.7/site-packages/novaclient/v1_1/__init__.py:30: UserWarning: Module novaclient.v1_1 is deprecated (taken as a basis for novaclient.v2). The preferable way to get client class or object you can find in novaclient.client module.
  warnings.warn("Module novaclient.v1_1 is deprecated (taken as a basis for "
/Users/marvin/pybossa/pybossa/env/lib/python2.7/site-packages/requests/packages/urllib3/connection.py:251: SecurityWarning: Certificate has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SecurityWarning
Traceback (most recent call last):
  File "run.py", line 21, in <module>
    app = create_app()
  File "/Users/marvin/pybossa/pybossa/pybossa/core.py", line 40, in create_app
    setup_uploader(app)
  File "/Users/marvin/pybossa/pybossa/pybossa/core.py", line 111, in setup_uploader
    uploader.init_app(app)
  File "/Users/marvin/pybossa/pybossa/pybossa/uploader/rackspace.py", line 49, in init_app
    region=app.config['RACKSPACE_REGION'])
  File "/Users/marvin/pybossa/pybossa/env/lib/python2.7/site-packages/pyrax/__init__.py", line 438, in _wrapped
    return fnc(*args, **kwargs)
  File "/Users/marvin/pybossa/pybossa/env/lib/python2.7/site-packages/pyrax/__init__.py", line 504, in set_credentials
    connect_to_services(region=region)
  File "/Users/marvin/pybossa/pybossa/env/lib/python2.7/site-packages/pyrax/__init__.py", line 626, in connect_to_services
    cloudservers = connect_to_cloudservers(region=region)
  File "/Users/marvin/pybossa/pybossa/env/lib/python2.7/site-packages/pyrax/__init__.py", line 679, in connect_to_cloudservers
    extensions = cs_shell._discover_extensions("1.1")
AttributeError: 'OpenStackComputeShell' object has no attribute '_discover_extensions'
```

What fixed the issue:
pinning python-novaclient to version 2.26.0:
```
pip install python-novaclient==2.26.0
```

**Comment by therealmarv** [comment]
Just additional note: all versions higher than 2.26.0 of python-novaclient fail the same way.

**Comment by briancurtin** [comment]
This was fixed in pyrax 1.9.5 last week.

Issue #571 and PR #573

**Comment by therealmarv** [comment]
ok thx! Will try to update Pyrax very soon! :)

**Comment by twig** [comment]
Any luck with this?

**Comment by briancurtin** [comment]
See the message a few inches above this: https://github.com/rackspace/pyrax/issues/575#issuecomment-138334404
