### ISSUE TITLE
dns.list_ptr_records() throws error

### ISSUE THREAD

**Issue by kynx** [rackspace/pyrax#590]
Hi,

I'm following the `samples/cloud_dns/list_ptr_records.py` example to the letter, but always get the following error when using the UID of a valid server (novaclient deprecation warnings omitted):

```
Traceback (most recent call last):
  File "./test.py", line 38, in <module>
    ptr_records = dns.list_ptr_records(server)
  File "/usr/local/lib/python2.7/site-packages/pyrax/clouddns.py", line 1354, in list_ptr_records
    return self._manager.list_ptr_records(device)
  File "/usr/local/lib/python2.7/site-packages/pyrax/clouddns.py", line 952, in list_ptr_records
    device_type = self._resolve_device_type(device)
  File "/usr/local/lib/python2.7/site-packages/pyrax/clouddns.py", line 944, in _resolve_device_type
    "or a CloudLoadBalancer." % device)
pyrax.exceptions.InvalidDeviceType: The device '<Server: [fqdn of server]>' must be a CloudServer or a CloudLoadBalancer.
```

Interestingly it works if I pass it a load balancer, so it must be down to the comparison against `pyrax.CloudServer` around [L938](https://github.com/rackspace/pyrax/blob/master/pyrax/clouddns.py#L938), but I'm not familiar enough with the code to know what it should be instead.

**Comment by kynx** [comment]
Looks like this has been fixed in the latest release.
